### ISSUE TITLE
Error in orig[[nm]][, j, ..., drop = drop] :    incorrect number of dimensions

### ISSUE THREAD

**Issue by GK0745** [jimrperkins/NormqPCR#1]
Hi,
I am new to R and the packages, I am trying the NormqPCR. 
 "Error in orig[[nm]][, j, ..., drop = drop] : 
  (subscript) logical subscript too long" shows up when I try to use the selectHKs. Can you please help.

**Comment by stamats** [comment]
Dear GK0745,
could you please provide a reproducible example. 
Best regards,
Matthias

**Comment by GK0745** [comment]
[control.txt](https://github.com/jimrperkins/NormqPCR/files/4380960/control.txt)
[scriptsused.txt](https://github.com/jimrperkins/NormqPCR/files/4380995/scriptsused.txt)
I have sent the example data and the scripts used.
Thank you.

**Comment by stamats** [comment]
Dear GK0745,

there are two things:
1) You need: contre <- sampleNames(geNorm.con.qPCRBatch).
2) It looks like, you have no biological replicates respectively you select only one sample (out of the three samples you seem to have in total). That is, mean and variance of the genes can not be computed. But these quantities are essential for computing the stability measures for the genes.

Best regards,
Matthias

**Comment by GK0745** [comment]
Dear Matthias,
Thank you for the suggestions and help.
I do have biological replicates.
Thanks a lot for your help.

Good Day
Gyanendra
